spring:
  application:
    name: PaymentsService
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5431/payments_db}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVICES:localhost:29093}

server:
  port: ${SERVER_PORT:8082}